# Generated by Django 4.0 on 2022-01-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app9_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
