# Generated by Django 3.1.3 on 2020-12-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app9_4', '0002_auto_20201215_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mobile',
        ),
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
