# Generated by Django 3.1.3 on 2020-12-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app9_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table=None,
        ),
    ]
