# Generated by Django 3.1.3 on 2020-12-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter Fullname : ', max_length=50)),
                ('contact_address', models.CharField(help_text='Enter Address : ', max_length=50)),
            ],
            options={
                'db_table': 'tbl_client',
                'ordering': ['-id'],
            },
        ),
    ]
