# Generated by Django 3.2.9 on 2021-12-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerText',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('banner_text', models.CharField(max_length=250)),
            ],
        ),
    ]
