# Generated by Django 3.1.4 on 2020-12-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
